main:
  img_path: "C:\\Users\\Admin\\Downloads\\result1.png"
  model_path: 'predict_segment/checkpoint/checkpoint_20251230_021157.pt'
  plotting: True

segment:
  patch_size: 512
  stride: 256
  save_patches: False